=== Maximeuuu/Deskastre/src/test/test-xml-niveaux/data/niveau/niveau.dtd
<!ELEMENT niveau (informations, proprietes, conditions, apparition, asteroides)>

	<!ELEMENT informations (titre, description)>
		<!ELEMENT titre (#PCDATA)>
		<!ELEMENT description (#PCDATA)>

	<!ELEMENT proprietes (background)>
		<!ELEMENT background (#PCDATA)>

	<!ELEMENT conditions (duree?, points?, asteroides?)>
		<!ELEMENT dureeMax (#PCDATA)>
		<!ELEMENT pointsMax (#PCDATA)>
		<!ELEMENT asteroidesMax (#PCDATA)>

	<!ELEMENT apparition (cycle, probabilite, min, max)>
		<!ELEMENT cycle (#PCDATA)> <!ATTLIST cycle unite CDATA #REQUIRED>
		<!ELEMENT probabilite (#PCDATA)>
		<!ELEMENT min (#PCDATA)>
		<!ELEMENT max (#PCDATA)>

	<!ELEMENT asteroides (asteroide+)>
		<!ELEMENT asteroide (#PCDATA)> <!ATTLIST asteroide probabilite CDATA #REQUIRED>

=== Maximeuuu/Deskastre/src/test/test-xml-niveaux/data/niveau/niveau1.xml
<?xml version="1.0" encoding="UTF-8" standalone="no" ?>
<!DOCTYPE niveau SYSTEM "niveau.dtd">

<niveau>

	<informations>
		<titre>Niveau 1</titre>
		<description>Un niveau de test</description>
	</informations>

	<proprietes>
		<background>chemin_image.jpg</background>
		<!--<musique>chemin_musique.mp3</musique>-->
	</proprietes>

	<conditions>
		<dureeMax>100</duree>
		<pointsMax>1000</points>
		<asteroidesMax>10</asteroides>
	</conditions>

	<apparition>
		<cycle unite="ms">1000</cycle> <!-- temps entre chaque apparition -->
		<probabilite>0.5</probabilite> <!-- probabilité d'apparition d'un asteroide -->
		<min>0</min> <!-- nombre d'asteroides min sur l'écran -->
		<max>5</max> <!-- nombre d'asteroides max sur l'écran -->
	</apparition>

	<asteroides> <!-- futur nom : obstacles ? -->
		<!-- remplacer par juste le nom de l'asteroide ? "ast1" -->
		<asteroide probabilite="0.2">asteroides/ast1.xml</asteroide>
		<asteroide probabilite="0.2">asteroides/ast2.xml</asteroide>
		<asteroide probabilite="0.2">asteroides/ast3.xml</asteroide>
		<asteroide probabilite="0.2">asteroides/ast4.xml</asteroide>
		<asteroide probabilite="0.2">asteroides/ast5.xml</asteroide>
	</asteroides>

</niveau>
